version: "3.8"

services:
  backend:
    container_name: voting-backend
    build: ./app
    ports:
      - "8080:8080"
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    volumes:
      - ./app:/usr/src/app/app


  redis:
    container_name: redis
    image: 'bitnami/redis:latest'
    expose:
      - "6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes